- name: "Multimedia Communication"
  icon: "heart"
  description: "I have the ability to edit videos, design, be able to program in arduinos and rasperri pi, design, program, among other things.."

- name: "UX Design"
  icon: "laptop"
  description: "My great passion is to create websites and applications where the user can find what they want quickly and effectively."

- name: "Designer"
  icon: "pencil"
  description: "One of my skills has been to design logos and create advertisements for certain brands so that they become known and can reach their customers in a creative and trained way."
